-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Anamakine: 127.0.0.1
-- Üretim Zamanı: 12 Oca 2024, 10:18:02
-- Sunucu sürümü: 10.4.32-MariaDB
-- PHP Sürümü: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `oyunlar`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `admin`
--

CREATE TABLE `admin` (
  `kullanici_adi` varchar(50) DEFAULT NULL,
  `sifre` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

--
-- Tablo döküm verisi `admin`
--

INSERT INTO `admin` (`kullanici_adi`, `sifre`) VALUES
('oyunadmin', 'elvedahaziran163');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `oyunlar`
--

CREATE TABLE `oyunlar` (
  `id` int(11) NOT NULL,
  `oyun_tipi` varchar(255) DEFAULT NULL,
  `oyun_adi` varchar(255) DEFAULT NULL,
  `oyun_gorsel_kucuk` varchar(255) DEFAULT NULL,
  `oyun_gorsel_buyuk` varchar(255) DEFAULT NULL,
  `oyun_video` varchar(255) DEFAULT NULL,
  `oyun_aciklama` varchar(10000) DEFAULT NULL,
  `oyun_copy_mesaj` varchar(255) DEFAULT NULL,
  `oyun_arkaplan_renk` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Tablo döküm verisi `oyunlar`
--

INSERT INTO `oyunlar` (`id`, `oyun_tipi`, `oyun_adi`, `oyun_gorsel_kucuk`, `oyun_gorsel_buyuk`, `oyun_video`, `oyun_aciklama`, `oyun_copy_mesaj`, `oyun_arkaplan_renk`) VALUES
(2, 'populer', 'Diablo 4', 'img/f18.jpg', 'img/diabloo.jpg', 'video/diabloizle.webm', 'Diablo, Blizzard Entertainment tarafından geliştirilen efsanevi bir aksiyon rol yapma oyunudur. İlk olarak 1996 yılında piyasaya sürülen ve ardından birçok devam oyunu ve genişleme paketi ile güçlenen Diablo serisi, karanlık fantastik dünyası ve bağımlılık yaratan oynanışıyla milyonlarca oyuncuyu büyülemiştir.Diablo, Tristram kasabasının altındaki derin zindanlar ve cehennem alemleri gibi karanlık ve tehlikeli ortamlarıyla tanınır. Oyunun atmosferi, oyunculara gerilim dolu bir macera yaşatır.Oyuncular, oyuna başlarken bir karakter sınıfını seçerler. Savaşçı, Büyücü, Avcı gibi farklı sınıflar, oyunculara farklı yetenek setleri ve oyun tarzları sunar.Oyunun dünyası rastgele üretilen haritalarla doludur, bu da her oyunun benzersiz ve keşfedilecek yeni bir dünya sunduğu anlamına gelir. Her seferinde farklı bir deneyim yaşayarak oyunun tekrar oynanabilirliğini artırır.Diablo evreni, oyuncuların karşılaşacakları devasa ve zorlu boss savaşlarıyla ünlüdür. Bu epik mücadeleler, strateji ve yetenek gerektiren zorlu sınavlar sunar.Oyuncular, oyun ilerledikçe daha güçlü eşyalar ve yetenekler kazanırlar. Bu, karakterinizi istediğiniz şekilde özelleştirmenizi ve güçlendirmenizi sağlar.Diablo, unutulmaz bir hikaye, çarpıcı grafikler ve sürükleyici oynanışıyla oyun dünyasında klasikleşmiş bir başyapıttır. Karanlığın derinliklerine dalın, zindanları keşfedin ve Diablonun kötü güçleriyle yüzleşin. Unutulmaz bir macera sizi bekliyor!', '2024 Diablo IV. All rights reserved.', '521005'),
(3, 'populer', 'Spider Man', 'img/f1.jpg', 'img/f1.jpg', 'video/spiderizle.webm', 'Marvel iş birliği ile Insomniac Games tarafından geliştirilen ve Nixxes Software tarafından PCye optimize edilen PC için Marvels Spider-Man Remastered, Marvelın New York şehrindeki büyük suçlarla ve simgesel kötü karakterlerle savaşan, deneyimli bir Peter Parkerı tanıtıyor. Aynı zamanda Marvelın New York şehrinin kaderini omuzlarında taşıyan Peter, karmakarışık kişisel hayatı ile kariyerini dengede tutmak için mücadele ediyor. Simgesel Marvel kötü karakterleri New York şehrini tehdit edince, Peter Parker ile Spider-Manin dünyaları çarpışır. Peterın şehri ve sevdiklerini kurtarması için ayaklarının üzerinde durması ve daha da muhteşem olması gerekiyor. Spider-Man gibi hissedin Maske ardında geçen sekiz yılın ardından, Peter Parker artık suçla savaşmakta bir usta olmuştur. Doğaçlama dövüşler, dinamik ve akrobatik hareketler, şehirde akıcı gezinme ve çevresel etkileşimler ile çok daha deneyimli bir Spider-Manin tüm gücünü hissedin.New York şehri Marvels Spider-Man ile hayat buluyor. Hayat dolu mahallelerde ağ atarak gezinin ve Marvel ile Manhattanın nefes kesici manzaralarını izleyin. Bu etkileyici aksiyon oyununda, kötüleri destansı bir şekilde saf dışı bırakmak için çevreyi kullanın. Asla Uyumayan Şehir içeriğinin bütünüyle tadını çıkarın Marvels Spider-Man Remasteredın ana hikâyesinin ardından, keşfedilecek ilave görevlere ve mücadelelere sahip, üç hikâye bölümü içeren Marvels Spider-Man: Asla Uyumayan Şehir ile Peter Parkerın yolculuğunun devamını deneyimleyin.', '2024 Spider Man. All rights reserved.', '080d6b'),
(5, 'populer', 'War Thunder', 'img/f2.jpg', 'img/war.jpg', 'video/warthunderizle.webm', 'War Thunder, Gaijin Entertainment tarafından geliştirilen ve           yayımlanan bir çevrimiçi savaş oyunudur. Oyun, II. Dünya Savaşından           Soğuk Savaşa kadar uzanan geniş bir zaman diliminde geçen gerçekçi ve           aksiyon dolu savaş deneyimini oyunculara sunmaktadır.Tanklar, uçaklar,           gemiler ve helikopterler gibi farklı savaş araçları arasından seçim           yaparak savaşın kontrolünü elinize alın. Her bir aracın özel           özellikleri ve avantajları bulunmaktadır.Gerçekçi grafikleri ve           ayrıntılı fizik motoruyla oyunculara sürükleyici bir savaş deneyimi           sunar. Hava, kara ve deniz savaşlarında detaylı araç modelleri ve           çevre özellikleriyle kendinizi gerçek bir savaş alanında           bulacaksınız.Oyuncular, tecrübe kazanarak ve araştırma yaparak yeni           araçlar, modüller ve yetenekler açabilirler. Bu, oyuncuların kendi           stratejik tarzlarına uygun bir ordu inşa etmelerini sağlar.War           Thunder, gerçekçi savaş simülasyonu seven oyuncular için heyecan           verici bir deneyim sunar. Tarihi araçlarla dolu geniş bir açık dünya           savaş ortamında stratejinizi belirleyin ve zafer için savaşın!', '2024 War Thunder. All rights reserved.', '540d46'),
(6, 'populer', 'EA SPORTS FC 24', 'img/f19.jpg', 'img/fcsport.jpg', 'video/sportizle.webm', 'EA SPORTS FC 24, Dünya Oyununun yeni çağıdır: 19.000+ tam lisanslı           oyuncu, 700+ takım ve 30+ lig, bugüne kadar PCde yaratılan en özgün           futbol deneyiminde birlikte oynuyor. Her maçta benzersiz gerçekçiliğe           güç veren üç modern teknolojiyle kendinizi oyuna daha yakın hissedin.           HyperMotionV, Opta tarafından optimize edilen OyunTarzları ve           geliştirilmiş Frostbite Oyun Motorunun yanı sıra PCde canlı ve           optimize edilmiş görselleri ortaya çıkaran yeni grafik ayarları ile           HyperMotionV, oyunu gerçekten oynandığı şekilde yakalıyor; 180den           fazla profesyonel erkekler ve kadınlar maçından hacimsel verileri           kullanarak maç içindeki hareketlerin gerçek hayattaki sahada yaşanan           aksiyonu doğru şekilde yansıtmasını sağlıyor.Opta ve diğer kaynaklardan alınan verileri           yorumlayarak her oyuncunun gerçekçiliğini ve bireyselliğini artıran           imza yeteneklere dönüştürüyor. Geliştirilmiş Frostbite Oyun Motoru,           Dünyanın Oyununu gerçekçi ayrıntılarla sunarak her maça yeni bir           sürükleyicilik seviyesi ekliyor. Yepyeni Ultimate Team           Geliştirmeleriyle kulüp efsanelerini yetiştirin ve oyuncularınızı           geliştirin, hayalinizdeki XIi kurarken kadın futbolcuları sahada           erkek oyuncuların yanında karşılayın. Teknik Direktör ve Oyuncu           Kariyerinde kendi hikayenizi yazın, Clubs ve VOLTA FOOTBALLda çapraz           oyun ile sahada arkadaşlarınıza katılın. EA SPORTS FC 24, futbolun           daha yenilikçi geleceğinin bir sonraki bölümüdür.', '2024 EA SPORTS FC 24. All rights reserved.', '086b0f'),
(7, 'populer', 'Counter Strike 2', 'img/f20.jpg', 'img/counter.jpg', 'video/counterstrike.webm', 'Counter Strike, Valve Corporation tarafından geliştirilen ve dünya           genelinde milyonlarca oyuncuya ulaşan birinci şahıs nişancı (FPS)           oyununun efsanevi bir temsilcisidir. İlk olarak 1999 yılında Half-Life           modu olarak başlayan serüveni, kısa sürede oyun dünyasının en popüler           ve rekabetçi oyunlarından biri haline geldi.Oyuncular, terörist veya           anti-terörist ekibine katılarak stratejik görevlerde yer alır.           Teröristler bomba kurmaya çalışırken, anti-teröristler bombayı           engellemek ve rehine kurtarmak gibi görevleri yerine getirmeye           çalışır.Counter Strike, takım çalışmasını vurgulayan taktiksel bir           oyun sunar. Harita bilgisi, silah seçimi, stratejik pozisyon alma ve           hızlı refleksler gibi faktörler, oyuncuların başarılı olmasında önemli           rol oynar.Counter Strike, geniş bir silah ve ekipman yelpazesi sunar.           Oyuncular, oyun içinde para kazanarak veya görevleri tamamlayarak           silahlarını ve ekipmanlarını yükseltebilirler.Oyuncular, rekabetçi           modda diğer oyunculara karşı yarışabilir ve bir rütbe sistemine dahil           olabilirler. Bu, oyuncuların yeteneklerine göre eşleşmeler yaparak           daha rekabetçi bir deneyim yaşamalarını sağlar.Counter-Strike, dünya           genelinde birçok büyük e-spor turnuvasına ev sahipliği yapar.           Profesyonel oyuncular, büyük ödüller için yarışır ve milyonlarca           izleyici, oyunun e-spor arenasını takip eder.Counter Strike, oyun           dünyasında bir klasiğe dönüşmüş, rekabetçi aksiyon oyunu olarak           kendine sağlam bir yer edinmiştir. Hala güncellenmeye devam eden oyun,           oyunseverlere yüksek tempolu ve heyecan dolu bir oyun deneyimi sunmaya           devam etmektedir.', '2024 Counter Strike 2. All rights reserved.', '341c04'),
(8, 'populer', 'Battlefield', 'img/batttttt.jpg', 'img/batttttt.jpg', 'video/battizle.webm', 'Eleştirmenlerden tam not alan bu birinci şahıs nişancı oyununda, büyük           Battlefield topluluğuna katılıp 1. Dünya Savaşının destansı           muharebelerinde yer alın. Eleştirmenlerin gözdesi Battlefield, Games           Critics Awards Best of E3 2016: En İyi Aksiyon Oyunu ve gamescom 2016           En İyi Aksiyon Oyunu ödüllerine layık görüldü. Topyekün savaşın           doğuşuna Battlefield ile tanık olun. Macera dolu harekat modunda savaş           halindeki dünyayı keşfedin ya da 64 oyuncu içeren çok oyunculu           destansı takım savaşlarına katılın. Piyade olarak savaşın ya da           inanılmaz kara, hava ve deniz vasıtalarını kontrol edin. Yeni çok           oyunculu haritalar, yeni silahlar ve daha fazlasını içeren dört adet           temalı genişletme paketini oynayın. Kızıl Baron Paketi, Arabistanlı           Lawrence Paketi ve Hellfighter Paketi,ünlü kahramanlardan ve           birliklerden ilham alınan temalı silahlar, vasıtalar ve amblemler           edinin.', '2024 Battlefield. All rights reserved.', '010327'),
(9, 'populer', 'Forza Horizon 5', 'img/f22.jpg', 'img/f22.jpg', 'video/forza.webm', 'Efsanevi Horizon Maceranız sizi bekliyor! Dünyanın en harika           arabalarından yüzlercesiyle birlikte sınırsız, eğlenceli sürücülük           aksiyonuyla Meksikanın capcanlı ve her daim gelişmekte olan açık           dünya manzaraları eşliğinde,sınırsız, eğlence dolu nefes kesici           seferlere önderlik edin. Çarpıcı kontrasta ve güzelliğe sahip bir           dünyayı; canlı çölleri, yemyeşil ormanları, tarihi şehirleri, gizli           harabeleri, el değmemiş plajları, geniş kanyonları ve karlı kaplı           yüksek volkanik dağı keşfedin. Sevdiğiniz aktivitelere katılım           yapmanız üzerine sizi ödüllendiren yüzlerce mücadeleyi içeren yoğun           bir karşılaşmanın içine dalıverin.Yeni karakterlerle tanışın ve           onların Horizon Hikâyelerinin akıbetini belirleyin. Yeni etkinlikler,           mücadeleler, koleksiyon eşyaları, ödüller ve keşfedilmeyi bekleyen           bölgeler için oyuna sık sık uğrayın. Her sezon biri diğerine asla           bezemeyecek şekilde eşsiz olacak. Diğer oyuncularla takım oluşturun.           Sizi ve arkadaşlarınızı aksiyonun içine çeken ve menüler, yükleme           ekranları veya lobiler olmadan eğlenmenizi sağlayan keyifli, üst düzey           mücadelelerden oluşan ve ardı ardına devam eden eğlenceli bir serinin           tadını çıkarmak için Horizon Arcadeye girin. Horizon Açıkta ve           Turlarda yeni arkadaşlar edinin, yeni topluluk hediye paylaşımıyla           yaratıcılığınızla oluşturduğunuz eserlerinizi paylaşın. Özel yarışlar,           mücadeleler, gösteriler ve tamamen yepyeni oyun modları yaratmak da           dâhil olmak üzere, güçlü, yeni EventLab oyun araç setiyle kendi           eğlence anlayışınıza hitap eden eserler oluşturun. Açılır tavanları           açma ve kapama imkanı, fren kaliperlerini boyama ve daha fazlasını           içeren yeni seçeneklerle araçlarınızı her zamankinden daha çeşitli           şekillerde özelleştirin. Toplulukla, oluşturduğunuz özel eserleri           paylaşmak için yeni Hediye Paketleri özelliğini kullanın.', '2024 Forza Horizon 5. All rights reserved.', '538f22'),
(10, 'gundem', 'GTA 5', 'img/f8.jpg', 'img/f8.jpg', 'video/gta5.webm', 'Genç bir serseri, inzivaya çekilmiş bir banka soyguncusu ve ürkütücü           bir psikopat, kendilerini suç dünyasının, ABD hükümetinin ve eğlence           sektörünün karışık ağlarında buluyor. Kendileri de dahil, hiç kimseye           güvenemedikleri acımasız bir şehirde tehlikeli soygunlar yapmayı           başarmak zorundalar.Grand Theft Auto V, Rockstar Games tarafından           yayımlanan efsanevi bir açık dünya aksiyon-macera oyunudur. İlk olarak           2013 yılında piyasaya sürülen GTA 5, büyüleyici bir hikaye, geniş bir           açık dünya ve çeşitli görevleri ile oyun dünyasında bir kilometre           taşıdır.Oyunculara 4k ve ötesinde çözünürlükle ve saniyede 60 kare           tazeleme hızıyla Los Santos ve Blaine County dünyasını keşfetme           fırsatını sunuyor. Oyun, fare ve klavye kontrollerinin yanı sıra doku           kalitesi, gölgelendirici, mozaikleme ve kenar yumuşatma gibi 25 farklı           ayar dahil, PCye özgü birçok özelleştirme tercihi sunuyor. Ayrıca           araç ve yaya trafiği kontrolü için nüfus yoğunluğu belirleyebilme           özelliği, iki veya üç monitör desteği, 3D uyumu ve tak-çalıştır           kumandalar için destek de seçeneklere dahil. Grand Theft Auto           Onlinenın PC sürümü, Soygunlar ve Rakip modları da dahil olmak üzere           konsollarda çıktığı tarihten beri yayınlanan tüm mevcut geliştirmeleri           ve Rockstarın oluşturduğu içeriği de içeriyor. Grand Theft Auto           Birinci Şahıs Bakışı Moduyla son derece detaylı Los Santos ve Blaine           County dünyasını bambaşka bir şekilde görme şansını veriyor. Ayrıca           Grand Theft Auto Vin PC sürümünde, Grand Theft Auto V ve Grand Theft           Auto Online içinden video çekmek, düzenlemek ve paylaşmak için gerekli           kreatif araçlardan oluşan Rockstar Editörü de mevcuttur. Rockstar           Edötrünün Yönetmen Modu, oyuncuların göze çarpan hikaye           karakterlerini, yayaları, hatta hayvanları dahi kullanarak kendi           sahnelerini de çekebilmesini sağlıyor. Oyuncular, ağır çekim, hızlı           çekim ve kamera filtreleri gibi düzenleme efektleriyle ve gelişmiş           kamera kullanımıyla birlikte GTA V radyo kanallarından kendi           şarkılarını ekleyebilecek veya oyun müziğinin çarpıcılığını dinamik           olarak kontrol edebilecektir.Grand Theft Auto V, oyun dünyasının en           popüler ve başarılı yapımlarından biridir. Eğlenceli hikayesi, geniş           açık dünyası ve çeşitli aktiviteleriyle oyunculara uzun süre unutulmaz           bir deneyim sunmaya devam etmektedir.', '2024 GTA 5. All rights reserved.', '171616'),
(11, 'gundem', 'Rust', 'img/f9.jpg', 'img/f9.jpg', 'video/rust.webm', 'Rust, Facepunch Studios tarafından geliştirilen ve yayımlanan çok           oyunculu bir hayatta kalma oyunudur. İlk olarak 2013 yılında erken           erişimde piyasaya sürülen Rust, acımasız bir açık dünyada hayatta           kalmaya çalışan oyuncular arasında rekabetçi bir deneyim sunar.Rust,           oyunculara geniş bir açık dünyada hayatta kalma mücadelesi verme           fırsatı sunar. Oyuncular, doğal kaynakları kullanarak yiyecek ve           malzemeler toplar, sığınaklar inşa eder ve diğer oyuncularla           etkileşime geçer.Oyunun başında her oyuncu, sadece bir tahta ve bir           taş ile başlar. Oyuncular, bu temel eşyaları kullanarak kendilerine           daha iyi ekipmanlar, silahlar ve sığınaklar inşa etmek zorundadırlar.           Rust, oyuncuların hayatta kalmak için sadece diğer oyuncularla değil,           aynı zamanda çevresel tehditlerle de mücadele etmelerini           gerektirir.Oyuncular, kendi sığınaklarını inşa edebilir ve savunma           önlemleri alabilirler. Ancak bu yapılar, diğer oyuncular tarafından           saldırıya uğrayabilir ve yağmalanabilir, bu da oyunculara stratejik           düşünce ve dayanıklılık gerektirir.Rust, oyunculara topluluklar kurma           ve diğer oyuncularla ticaret yapma fırsatı tanır. Topluluklar arasında           müttefiklikler ve rekabetler oluşabilir, bu da oyuna derinlik           katar.Rust, acımasız açık dünya deneyimi, zorlayıcı hayatta kalma           unsurları ve oyuncular arası etkileşimleriyle oyunseverlere kendine           özgü bir oyun sunar. Her an beklenmedik olayların yaşandığı bu dünyada           hayatta kalmak için strateji ve dayanıklılık gereklidir.', '2024 Rust. All rights reserved.', '6b3d08'),
(12, 'gundem', 'Red Dead Redemption ', 'img/f10.jpg', 'img/f10.jpg', 'video/reddead.webm', 'Red Dead Redemption 2, Rockstar Games tarafından geliştirilen ve           yayımlanan aksiyon-macera oyunudur. 2018 yılında piyasaya sürülen           oyun, Vahşi Batının epik atmosferinde geçen muazzam bir açık dünya           deneyimi sunuyor.Red Dead Redemption 2, Amerikan Vahşi Batısının           geniş ve detaylı bir haritasında geçer. Dağlardan vadilere,           kasabalardan ormanlık alanlara kadar zengin bir çevre sunar.Oyun,           Arthur Morgan adlı bir haydutun perspektifinden anlatılan etkileyici           bir hikayeye sahiptir. Çetesiyle birlikte hayatta kalmaya çalışan           Arthur, hem içsel çatışmalarla hem de dışsal tehditlerle yüzleşmek           zorundadır.Oyun, muhteşem grafikleri ve detaylı animasyonlarıyla           dikkat çeker. Hava durumu efektleri, gündüz-gece döngüsü ve detaylı           karakter animasyonları, oyunculara gerçekçi bir deneyim sunar.Oyun,           çevrimiçi çok oyunculu mod olan Red Dead Online sahiptir. Burada           diğer oyuncularla birlikte görevler yapabilir, çeteler kurabilir ve           Vahşi Batıdaki maceranızı genişletebilirsiniz.Red Dead Redemption 2,           sadece muazzam açık dünya atmosferi ve detaylarıyla değil, aynı           zamanda etkileyici bir hikaye anlatımı ve zengin oyun mekaniğiyle de           öne çıkan bir başyapıttır. Vahşi Batının güzellikleri ve           tehlikeleriyle dolu bu epik macera, oyuncuları unutulmaz bir deneyime           sürükler.', '2024 Red Dead Redemption 2. All rights reserved.', 'bf0d0d'),
(13, 'gundem', 'Dota', 'img/f11.jpg', 'img/dotaa.jpg', 'video/dota.webm', 'Dota 2, Valve Corporation tarafından geliştirilen ve dünya genelinde           büyük bir oyuncu kitlesi tarafından oynanan çok oyunculu çevrimiçi           savaş arenası oyunudur. İlk olarak 2013 yılında piyasaya sürülen oyun,           stratejik düşünce, takım çalışması ve yetenekli karakter kullanımına           dayanan rekabetçi bir deneyim sunar.Dota 2, oyunculara 120den fazla           farklı kahraman seçeneği sunar. Her kahramanın kendine özgü           yetenekleri, güçleri ve oynanış stilleri bulunur, bu da her maçın           benzersiz bir deneyim olmasını sağlar.Oyuncular, iki takım halinde           mücadele eder ve her takım beşer oyuncudan oluşur. Takımlar,           haritadaki önemli noktalara saldırılar düzenler, stratejik avantajlar           elde etmeye çalışır ve düşmanlarını alt etmek için takım içi           koordinasyonu kullanır.Oyuncular, oyun içindeki maçlardan elde           ettikleri deneyim puanlarıyla kahramanlarını geliştirebilir, yeni           yetenekler ve eşyalar açabilirler. Bu, oyuncuların stratejik olarak           oyun içinde ilerlemelerini ve kendi oyun tarzlarına uygun kahramanları           keşfetmelerini sağlar.Dota 2, dünya genelinde büyük e-spor           turnuvalarına ev sahipliği yapar. The International gibi büyük           turnuvalar, milyonlarca dolarlık ödül havuzları ve büyük bir izleyici           kitlesiyle Dota 2yi rekabetçi oyun sahnesinde bir öncü haline           getirir.Dota 2, stratejik zekanın, takım işbirliğinin ve bireysel           yeteneklerin bir araya geldiği büyüleyici bir deneyimdir. Oyuncular,           kendi oyun tarzlarına uygun kahramanları seçip, takım stratejilerini           uygulayarak unutulmaz savaşlara katılır.', '2024 Dota. All rights reserved.', 'd45917'),
(14, 'gundem', 'Baldurs Gate', 'img/f12.jpg', 'img/f12.jpg', 'video/baldur.webm', 'Baldurs Gate, BioWare tarafından geliştirilen ve Black Isle Studios           tarafından yayımlanan efsanevi bir rol yapma oyunudur. İlk olarak 1998           yılında piyasaya sürülen bu klasik, unutulmaz hikayesi ve derin oyun           mekaniğiyle türünün öncülerinden biridir. Baldurs Gate, oyunculara           epik bir hikaye sunar. Kara Büyücü Sarevokun tehdidi altındaki Sword           Coast dünyasında geçen bu hikaye, oyuncuların kendi karakterlerini           oluşturup geliştirmelerine olanak tanır.Oyun, Dungeon & Dragonsun 2.           Baskı kurallarına dayanır. Bu, oyunculara geniş bir karakter yaratma           ve özelleştirme özgürlüğü sağlar. Oyun içindeki diyaloglar ve           etkileşimler de D&D evreninin ruhunu taşır.Oyunculara keşfedilecek           büyük ve detaylı bir açık dünya sunar. Şehirler, ormanlar, mağaralar           ve daha fazlasını içeren bu dünya, oyunculara serbestçe dolaşma ve           keşfetme fırsatı verir.Oyun stratejik savaşları ile de dikkat çeker.           Gerçek zamanlı savaşlarda karakterlerinizi yönetirken, oyunun           duraklatma özelliği sayesinde stratejilerinizi planlamanıza olanak           tanır.Fantastik bir dünyada geçen epik bir serüven arayan oyuncular           için unutulmaz bir deneyim sunar.', '2024 Baldurs Gate. All rights reserved.', '1276a0'),
(15, 'gundem', 'Escape the Backrooms', 'img/escp2.jpg', 'img/escp2.jpg', 'video/escape.webm', 'Popüler creepypasta efsanesine dayanan arka odalardaki ürkütücü           derecede seviyelerin görünüşte sonsuz genişliğini keşfedin. Her           seviye, yol boyunca tehlike ile kaçmak için farklı yollar içerir.           Gerçekçi grafikler, minimal kullanıcı arayüzleri ve kasvetli ambiyans           sürükleyici bir deneyim sağlayacaktır. En fazla 4 oyuncudan oluşan bir           ekiple arka odaları keşfedin. Takım arkadaşlarınız haritanın diğer           alanlarına giremeyebileceğinden ve ekibinizin her üyesi kaçmak için           çıkışı canlı olarak bulmak zorunda olduğundan dikkatli olun. Hiçbir           gezgin geride kalmayacak. Düzenli içerik güncellemeleri ile daha           fazlasını ekleyerek arka oda bilgisine dayanan 20den fazla benzersiz           seviyeden geçin. Her seviye, yol boyunca çeşitli tehlikelerle kaçmak           için farklı bir yol sunar. Her köşeyi kontrol edin, böylece arka           odalardaki 12 düşman varlıktan biri tarafından hazırlıksız           yakalanmazsınız,hayatta kalmak istiyorsanız her birinin hızlı bir           şekilde öğrenmeniz gereken kendi mekanikleri vardır. Yakınlık sesli           sohbeti ile takım arkadaşlarınızla iletişim kurun. Arka odaların kafa           karıştırıcı genişliğinde kolayca kaybolabileceğiniz için ekibinizden           çok uzaklaşmadığınızdan emin olun. Varlıklar da sizi duyabilir, bu           nedenle herhangi bir tehlikenin yakınında olduğunuzda sessiz kalın.', '2024 Escape the Backrooms. All rights reserved.', 'c2bd30'),
(16, 'gundem', 'Sengoku Dynasty', 'img/f24.jpg', 'img/f24.jpg', 'video/sengoku.webm', 'Açık dünya,şehir kurma ve yaşam simülasyonunu hayatta kalma öğeleriyle           birleştiren Sengoku Dynasty, çok türlü ve heyecanlı bir deneyim           sunuyor. Feodal Japonyanın çalkantılı dönemlerinde sıfırdan           başlayarak kuracağın hanedanlığın lideri ol. Tek başına veya çok           oyunculu eşli modda ister birinci ister üçüncü şahıs kamera açısında           oyna. Kıtlık ve savaşın harap ettiği Japonyada kendine bir hayat kur,           bir köy inşa et ve hanedanlığının temellerini at. İster tek başına,           ister çok oyunculu eşli modda oyna ve bu muhteşem açık dünyayı           keşfederken hayatta kalmak ve köy topluluğunu desteklemek için kaynak           topla, üret, avlan, yapı inşa et ve tarım yap. Zorlu düşmanlarla           savaş, harika bir lider ol ve mirasını koru. Doğanın güzelliklerini           deneyimle ve kadim ritüellere katılarak kutsal gizemleri açığa çıkar.           Sengoku Dynasty ile Ortaçağ Japonyası hakkında pek çok şey öğren. Bir           Lider, Zanaatkâr, Savaşçı veya Keşiş olmayı seçerek efsanevi bir           maceraya atıl.', '2024 Sengoku Dynasty. All rights reserved.', '41ae12'),
(18, 'onecikan', 'PUBG', 'img/f13.jpg', 'img//puggg.jpg', 'video//pubgg.webm', ' PlayerUnknowns Battlegrounds, PUBG, Corporation tarafından           geliştirilen ve yayımlanan bir battle royale oyunudur. İlk olarak 2017           yılında piyasaya sürülen PUBG, oyuncuları bir adaya bırakarak hayatta           kalmaya ve diğer oyuncularla mücadele etmeye zorlayan sürükleyici bir           deneyim sunar.PUBG, 100 oyuncunun bir uçağın üzerinden adaya atlayarak           hayatta kalmak için mücadele ettiği bir battle royale formatında           oynanır. Oyun ilerledikçe, harita alanı giderek daralır, bu da           oyuncuları çatışmaya zorlar.Oyun, çeşitli haritaları içerir. Geniş           açık alanlardan şehir bölgelerine kadar farklı temalara sahip           haritalar, oyunculara çeşitli stratejik seçenekler sunar.PUBG,           oyunculara geniş bir silah yelpazesi ve ekipman seçenekleri sunar.           Oyuncular, oyuna başladıklarında çevrelerindeki binalardan silah ve           ekipman toplarlar, daha sonra düşmanlarla çatışmalara girmek için bu           ekipmanları kullanırlar.Oyunda kullanılabilir araçlar, oyuncuların           harita üzerinde hızlı ve taktiksel bir şekilde hareket etmelerine           olanak tanır. Araçlar, hayatta kalma şansını artırmak ve stratejik           avantajlar elde etmek için önemlidir. PUBG, solo oyunculara, iki           kişilik takımlara veya dört kişilik takımlara katılma seçeneği sunar.           Oyuncular, tek başlarına veya arkadaşlarıyla birlikte oynayarak           rekabet edebilirler.PlayerUnknowns Battlegrounds, battle royale           türünün popülerleşmesine öncülük eden oyunlardan biridir. Zorlu           rekabet, stratejik düşünce ve anlık tepki gerektiren oyun mekaniği,           PUBGyi heyecan verici ve bağımlılık yaratan bir deneyim haline           getirir.', '2024 PUBG. All rights reserved.', '22190a'),
(19, 'onecikan', 'ELDEN RING', 'img/f14.jpg', 'img/eldenringg.jpg', 'video/elden.webm', 'Elden Ringin gücünü kullan ve Lands Betweende bir Elden Lord ol.           Çeşitli olayları içinde barındıran açık arazilerin, karmaşık ve üç           boyutlu tasarımlara sahip büyük zindanlarla buluştuğu devasa bir           dünyadır. Yolculukların sırasında, bilinmeyeni keşfetmenin ve           tehditlerin üstesinden gelmenin verdiği o tatmin edici başarım hissi           seni bekliyor. Karakterinin görünüşünü özelleştirebilmenin yanı sıra           kuşanabildiğin silahlardan, zırhlardan ve büyülerden de dilediğin           kombinasyonu oluşturabilirsin. Karakterini oyun tarzına göre           şekillendirebilir, istersen güçlü bir savaşçı olmak için fiziksel           gücünü arttırabilir, istersen de bir büyü ustası olabilirsin. Parçalar           halinde işlenen çok katmanlı bir hikâyedir. Karakterlerin çeşitli           düşüncelerinin Lands Betweende kesiştiği destansı bir drama. Diğer           oyuncularla doğrudan etkileşime geçebileceğin ve birlikte seyahat           edebileceğiniz çok oyunculu modun yanı sıra oyun, başkalarının           varlığını hissetmeni sağlayacak benzersiz bir eşzamansız çevrimiçi           unsuru da destekliyor.', '2024 Elden Ring. All rights reserved.', '080d6b'),
(20, 'onecikan', 'PAYDAY', 'img/f15.jpg', 'img/f15.jpg', 'video/payday.webm', 'Payday 2, Overkill Software tarafından geliştirilen ve Starbreeze           Studios tarafından yayımlanan birinci şahıs nişancı (FPS) ve           kooperatif oynanabilirliğe sahip bir aksiyon oyunudur. İlk olarak 2013           yılında piyasaya sürülen oyun, oyuncuları bir suç çetesinin içine           sokarak büyük soygunlar ve taktiksel çatışmalarla dolu bir dünyaya           taşır.Payday 2, oyunculara çeşitli soygun görevleri sunar. Bankalar,           müzeler, depolar ve daha birçok mekan, oyuncuların takım           arkadaşlarıyla birlikte plan yaparak ve koordineli bir şekilde           soygunları gerçekleştirmeleri için mekanlar sağlar. Oyunda farklı           karakter sınıfları ve uzmanlıklar bulunur. Oyuncular, soygunlarını           daha iyi planlamak ve gerçekleştirmek için çeşitli beceri ağaçlarından           yararlanabilirler. Oyuncular, geniş bir silah ve ekipman yelpazesi           arasından seçim yapabilirler. Her oyuncu, oyun tarzına uygun silahları           ve ekipmanları seçerek karakterini özelleştirebilir.Payday 2, dört           kişilik bir ekip kurma ve diğer çetelerle rekabet etme olanağı sunan           güçlü bir çevrimiçi oynanışa sahiptir.', '2024 PAYDAY. All rights reserved.', '080d6b'),
(21, 'onecikan', 'Age of Empires', 'img/f16.jpg', 'img/f16.jpg', 'video/empire.webm', '20 yıl önce yayınlanan, efsanevi gerçek zamanlı strateji oyunu Age of           Empires, nihai şekliyle Windows 10 bilgisayarlar için dönüyor.Age of           Empires, oyunculara antik çağdan Orta Çağa, Rönesansa ve hatta           İkinci Dünya Savaşına kadar uzanan bir dizi farklı dönemi keşfetme           şansı verir. Oyuncular, seçtikleri medeniyeti yönetirken kaynak           toplama, ordu oluşturma ve düşmanlarla savaşma gibi temel stratejik           unsurları deneyimleyerek kendi imparatorluklarını inşa ederler. Resmi           olarak yayınlanmış tüm içerikleri modernleştirilmiş oynanışla, yepyeni           görsellerle ve bir sürü başka yeni özeliklerle bir araya getiren Age           of Empires: Definitive Edition, eksiksiz bir gerçek zamanlı strateji           paketidir. Yeni anlatım ve tempoyla 40 saatten fazla oynanış sunan           güncellenmiş seferlerle meşgul olun; yeni, rekabetçi özellik ve           modlarla 8 oyuncuya kadar destek veren çoklu oyuncuda çevrimiçi           mücadele edin.Yenilenmiş animasyonlarla 4K HD görselleri tecrübe           edin.Senaryo editörüyle yaratıcılığınızı konuşturun ve           oluşturduklarınızı paylaşın. Age of Empiresa dalış yapmak için daha           iyi bir zaman olamaz. Tarihe tekrar hoş geldiniz.', '2024  Age of Empires. All rights reserved.', 'f4d53a'),
(22, 'onecikan', 'Crysis Remastered', 'img/f17.jpg', 'img/crysisss.jpg', 'video/crysis.webm', 'Crytekin sunduğu klasik birinci şahıs nişancı oyun; aksiyon dolu oyun           tasarımı, korumalı dünyası,nefes kesici ve efsanevi savaşlarıyla geri           döndü. Hem de tekrar düzenlenerek yeni nesil donanım ürünleri için           optimize edilen grafikleriyle! Basit bir kurtarma operasyonu olarak           başlayan bu macera, uzaylı istilacıların Kuzey Koreyi oluşturan           adalar kümesine üşüşmesiyle yepyeni bir savaş sahnesine dönüşüyor.           Nanozırhın gücünü avantaja çeviren oyuncular, devriye gezen düşmanlara           gizlice yaklaşmak için görünmez olabilir veya güç düzeyini artırarak           araçları paramparça edebilir. Nanozırhın hızı, gücü, koruma kapasitesi           ve görünmezlik özelliği her türlü mücadelede karşılaşılan zorluklara           yaratıcı çözümler bulunmasını sağlar. Kapsamlı modüler silah           cephanesiyse oynama tarzını belirleme konusunda benzeri görülmemiş bir           denetim olanağı sunar. Bulunduğun ortam sürekli olarak değiştiğinden           bu devasa ve korumalı dünyada düşmanlarına hükmetmek için,           taktiklerini ve ekipmanını koşullara göre adapte et. Nanozırhının           hızı, gücü, koruma kapasitesi ve görünmezlik özelliğinden           yararlanarak, her türlü mücadelede karşılaştığın zorluklara yaratıcı           çözümler bulabilirsin. Bulunduğun ortam sürekli olarak değiştiğinden,           buz kaplı ormanlardan uzaya kadar çeşitli yerlerdeki savaş alanlarına           hükmetmek için, taktiklerini koşullara göre adapte et. Diğer           oyunculardan ayırt etmekte zorlanacağın düşman karakterler seni           oyun tarzını stratejik ve esnek tutmaya iter. Yerçekimsiz ortam gibi           yeni zorluklarsa oyuncuların saldıran taraf olmasını ve süreci           adımlarıyla yönlendirmesini gerektirir. Olanaklarla dolu Crysis           dünyasında kendi yolunu sen belirle, engelleri yok et, araç           kullanmanın tadını çıkar ve çevreyi düşmanlarına karşı kullanarak           üstünlük elde et.', '2024 Crysis Remastered. All rights reserved.', '2164b5'),
(23, 'onecikan', 'Mount & Blade II', 'img/f25.jpg', 'img/f25.jpg', 'video/mountblade.webm', 'Savaş boruları ötüyor ve kuzgunlar toplanıyor. İmparatorluk iç           savaşlar yüzünden bölünmüş durumda. Sınırlarının ötesinde yeni           krallıklar yükseliyor. Kılıcını kuşan, zırhını giy, adamlarını topla           ve atına atlayarak Kalradyanın savaş meydanlarında zaferler kazan.           Egemenliğini kur ve eskisinin küllerinden yeni bir dünya yarat. Mount           & Blade II: Bannerlord büyük bir başarı elde eden orta çağ savaş           simülasyonu ve rol-yapma oyunu Mount & Blade: Warbandin heyecanla           beklenen devam oyunudur. Hiçbir oyun deneyiminin birbirinin aynı           olmadığı uçsuz bucaksız bir orta çağ sandbox haritasını keşfederek           fetihler gerçekleştirirken, kendi oyun tarzına uygun bir karakter           yarat ve geliştir. Klanınla Kalradyanın soyluları arasında yer           edinmeye çalışırken ordular topla, politikayla ilgilen, ticaretle           uğraş, silahlar yap, yoldaşlar edin ve topraklarını yönet. Mount &           Bladenin beceriye dayalı derin, sezgisel ve yön duyarlı dövüş           sistemini kullanarak gerçek zamanlı büyük savaşlarda, ister birinci,           ister üçüncü şahıs bakış açısından birliklerine önderlik et ve           askerlerinle birlikte savaş. Sıralamaya dayalı eşleştirmenin yanı           sıra, eğlence amaçlı oyun modları da içeren çok oyunculu oyunlarda           dünyanın dört bir yanından oyunculara karşı dövüş becerilerini sına ya           da Mount & Blade II: Özel Sunucu dosyalarıyla kendi sunucunu aç.           Bambaşka bir macera deneyimlemek için Mount & Blade II: Bannerlord –           Modlama Kitini kullanarak oyunu isteğine göre uyarla.', '2024 Mount & Blade II. All rights reserved.', '6b3008'),
(24, 'onecikan', 'Dead by Daylight', 'img/f26.jpg', 'img/f26.jpg', 'video/deadbydaylight.webm', 'Dead by Daylight, korku ve hayatta kalma türlerini bir araya getiren,           Behaviour Interactive tarafından geliştirilen bir çok oyunculu hayatta           kalma oyunudur. Oyun,hayatta kalmaya çalışan Hayatta Kalanlar ile           onları avlamaya çalışan acımasız bir Katil arasındaki gerilimli           mücadeleye odaklanır.Oyuncular, 4e 1 çok oyunculu deneyiminde,           hayatta kalmaya çalışan birinci şahıs bakış açısına sahip karakterleri           kontrol ederler. Hayatta kalanlar, harita üzerindeki jeneratörleri           tamir etmeye çalışarak kapıları açmaya ve kaçmaya çalışırken, Katil           ise avlanarak onları yakalamaya ve kurban etmeye çalışır. Oyunun temel           dinamikleri, gizlilik, strateji ve hızlı kararlar üzerine           kuruludur.Oyuncular, kendilerine özgü yeteneklere sahip Hayatta Kalan           ve Katil karakterleri arasından seçim yapabilirler. Her karakterin           farklı avantajları ve dezavantajları vardır, bu da oyuna derinlik           katar.Oyun, çeşitli korku temalı haritalarda geçer. Klostrofobik           ormanlardan, terkedilmiş şehir bölgelerine kadar farklı mekanlarda           oynanabilir.Oyuncular, oyun içinde deneyim kazanarak karakterlerini           geliştirebilirler. Gelişmiş ilerleme sistemi, yeni yeteneklerin           kilidini açma ve özelleştirilebilir eşyalar edinme imkanı sunar.Dead           by Daylight, aktif bir topluluğa sahiptir ve düzenli olarak           güncellemelerle desteklenir. Yeni Haritalar, karakterler ve oyun           mekaniği güncellemeleri, oyunculara sürekli yeni içerikler sunar.', '2024 Dead by Daylight. All rights reserved.', '6b1208'),
(25, 'populer', 'Dota', 'img/f11.jpg', 'img/f11.jpg', 'video/dota.webm', 'ghsjsjsdghdgsdsjsksdjjsdh', '2024 Dotat. All rights reserved.', '2164b5');

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `oyunlar`
--
ALTER TABLE `oyunlar`
  ADD PRIMARY KEY (`id`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `oyunlar`
--
ALTER TABLE `oyunlar`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
